\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{pbk}[2015/04/02 Portable Book Kit]
\LoadClass[openany]{book}
\RequirePackage{cmds}
\RequirePackage{graphicx}
\RequirePackage{epstopdf}
\RequirePackage{grffile}
\usepackage[T1]{fontenc}
\RequirePackage{makeidx}
\RequirePackage[linktoc=all]{hyperref}
\hypersetup{
    colorlinks,
    citecolor=black,
    filecolor=black,
    linkcolor=black,
    urlcolor=black
}
